export const productCategories = [
    {
        category: "ICE CREAMS",
        items: [
            "2-IN-1 STRAWBERRY & BLACK CURRENT",
            "ARUN MALAI KULFI BAR",
            "BAZOOKA (PINEAPPLE & JAMUN BAR)",
            "BELGIUM CHOCOLATE ICONE",
            "BERRY HEARTS",
            "BUTTERSCOTCH ICONE 100ML/125ML",
            "CASSATA SLICE EXOTIC 120ML",
            "CHOCO BUTTERSCOTCH SMILY",
            "CHOCO TOFFEE",
            "CHOCOBAR 55 ML",
            "CHOCOLATE - 50 ML ICONE",
            "CHOCOLATE - CUP 85 ML",
            "COTTON CANDY - 50ML ICONE",
            "COTTON CANDY WHALE BAR",
            "FRUIT CREME CUP",
            "FUN WHEEL",
            "IC SHAKES (STRAWBERRY, CHOCOLATE, MANGO)",
            "IC SW COOKIE & CREAM",
            "JOLLY TRAIN",
            "KACCHA MANGO CUP",
            "KESAR PISTA - 50 ML - ICONE",
            "LIPSTICK ORANGE/APPLE/MANGO/GRAPE BAR",
            "LITTLE LOVE",
            "LYCHEE BITES",
            "MANGO - 30ML ICONE",
            "MANGO BAR",
            "MINI BALL (CHOCO/VANILLA)",
            "MINI CHOCOBAR",
            "NEAPOLITAN (VANILLA STRAWBERRY)",
            "POPITOS APPLE BAR",
            "RASPBERRY BITES",
            "RASPBERRY CHOCOLATE TRUFFLE",
            "RED VELVET",
            "SPIRAL MANGO & LITCHI",
            "STRAWBERRY CUP 60ML",
            "TOFFEE - 30ML ICONE",
            "TRIO (RASP VANILLA MANGO) BAR",
            "TRIPLES (LEMON ORANGE & MINT)",
            "VANILLA BITES",
            "VANILLA ICONE 100ML",
            "LIKSTICK ORANGE BAR 50ML",
            "LIKSTICK APPLE BAR 50ML",
            "LIKSTICK MANGO BAR 50ML",
            "LIKSTICK GRAPE BAR 50ML",
            "ARUN MALAI KULFI BAR 55ML",
            "IC STRAWBERRY SHAKE 90ML",
            "IC COTTON CANDY SHAKE 90ML",
            "IC CHOCOLATE SHAKE 90ML",
            "IC MANGO SHAKE 90ML",
            "IC SW RECTANGLE 30ML",
            "IC SW COOKIE & CREAM 60ML",
            "Mango Delite",
            "STRAWBERRY CHEESE ICONE",
            "BLACK CURRANT ICONE 60ML",
            "BUTTERSCOTCH ICONE 100ML",
            "DOUBLE CHOCOLATE ICONE 100ML",
            "Belgium Chocolate",
            "RED VELVET ICONE 100ML",
            "BUTTERSCOTCH CUP 125ML",
            "ITALIAN DELIGHT CUP 125ML",
            "VANILLA CUP 125ML",
            "MILK FANTASY CUP 40ML",
            "MANGO CUP 125ML",
            "POPITOS APPLE BAR 22ML",
            "KACCHA MANGO CUP 22ML",
            "MINI BALL CHOCOLATE",
            "MINI BALL VANNILA",
            "RICH CHOC CUP 40ML",
            "COTTON CANDY PUSHUP",
            "BLACK CURRANT CUP 125 ML",
            "BELGIAN DONUT",
            "COTTON CANDY CONE",
            "IC SW CHOCO CAREMEL PENUT SAN",
            "IC SW REDVELVET SANDWICH 70ML",
            "DONUT - COOKIE & CREAM 15 ML"
        ]
    },
    {
        category: "COOL DRINKS",
        items: [
            "MOUNTAIN DEW",
            "MIRINDA(Bottle)",
            "7 UP",
            "PEPSI",
            "CHOCOLATE MILK SHAKE",
            "BELGIAN CHOCO MILKSHAKE",
            "VANNILA MILKSHAKE",
            "STRAWBERRY MILKSHAKE",
            "COLD COFFEE",
            "ROSE LASSY",
            "KESAR MILK",
            "BUTTER SCOTCH MILK SHAKE",
            "ORANGE CREAM SHAKE",
            "PREMIUM MALT",
            "ROSE MILK",
            "BADAM MILK",
            "1 RS CHOCOLATE",
            "1 RS ECLAIRS",
            "GALAXY CHOCOLATE",
            "20 RS CHOCOLATE (SNICKERS)",
            "35 RS CHOCOLATE (snickers)-brownie",
            "DOUBLE MINT",
            "TROPICANA- APPLE TETRA",
            "TROPICANA- APPLE",
            "TETRA APPLE",
            "TETRA GUAVA",
            "TETRA LITCHI",
            "TETRA MANGO",
            "TETRA SLICE",
            "TETRA MIXED FRUIT",
            "NIMBOOZ TETRA",
            "TROPICANA - MIXED",
            "TROPICANA - GUAVA",
            "MAA APPLE",
            "MAA - MANGO",
            "TROPICANA - LITCHI",
            "TROPICANA - POMOGRANATE",
            "TROPICANA - ORANGE",
            "WATER BOTTLE",
            "MAA MANGO",
            "MAAZA(BOTTLE) 250ML",
            "TETRA-MAAZA",
            "THUMS UP (BOTTLE) 250ML",
            "FANTA -BOTTLE 250ML",
            "FANTA - TIN 300ML",
            "COCA COLA -BOTTLE 250ML",
            "COCA COLA -TIN 300ML",
            "LIMCA - BOTTLE 250ML",
            "LIMCA - TIN 300ML",
            "SPRITE -BOTTLE 250ML",
            "SPRITE - TIN 300ML",
            "PULPY - ORANGE - BOTTLE",
            "KINLEY WATER BOTTLE - 500ML",
            "KINLEY WATER BOTTLE - 1LT",
            "MILK BADAM",
            "MILK ROSE",
            "MILK CHOCOLATE",
            "WATERMELON FRUIT",
            "TROPICANA APPLE",
            "TROPICANA MIXED"
        ]
    },
    {
        category: "SNACKS",
        items: [
            "SAMOSA",
            "EGG BONDA",
            "NORTH INDIAN SAMOSA",
            "CHILLIBAJI",
            "BREAD BAJI",
            "VAZHAKAI BAJI",
            "ULUNTHU VADAI",
            "POTATO BONDA",
            "PARUPPU VADAI",
            "NORMAL OMLETE",
            "NORTH INDIAN SAMOSA ",
            "Black sundal",
            "ONION BONDA",
            "BREAD OMLET",
            "PLAIN OMLETE"
        ]
    },
    {
        category: "BAKERY ITEMS",
        items: [
            "EGG PUFFS",
            "VEG PUFFS",
            "PANNEER PUFFS",
            "CHICKEN PUFFS",
            "CHICKEN SANDWICH",
            "PUTTING CAKE",
            "TEA CAKE",
            "COCANUT BUN",
            "COCONUT BUN ROLL",
            "BREAD",
            "WHEAT BREAD"
        ]
    },
    {
        category: "OTHERS",
        items: [
            "TEA",
            "TEA (Excess)",
            "COFFEE"
        ]
    },
    {
        category: "COMBO PACK SALES",
        items: [
            "TEA WITH EGG PUFFS",
            "TEA WITH PUDDING CAKE",
            "TEA WITH SAMOSA 2 NOS",
            "CHICKEN ROLL WITH PEPSI",
            "CHICKEN ROLL WITH 7 UP",
            "CHICKEN ROLL WITH MIRANDA",
            "CHICKEN ROLL WITH MOUNTAIN DEW"
        ]
    },
    {
        category: "BREAKFAST",
        items: [
            "RAVA KITCHADI",
            "RAVA KITCHADI (Parcel)",
            "ROAST",
            "EXTRA DOSA",
            "PARCEL DOSA",
            "PODI ROAST",
            "PAR PODI ROAST",
            "EGG ROAST",
            "PAR EGG ROAST",
            "EXTRA IDIYAPPAM",
            "POORI MASAL",
            "EXTRA POORI",
            "PARCEL POORI"
        ]
    },
    {
        category: "LUNCH",
        items: [
            "CURD RICE",
            "TOMOTA RICE",
            "PAR CURD RICE",
            "PAR TOMOTA RICE",
            "CHICKEN CHAPPATHI & GRAVY",
            "PARCEL CHICKEN CHAPPATHI",
            "PANNEER CHAPPATHI & GRAVY",
            "PARCEL PANNEER CHAPPATHI",
            "EGG CHAPATHI & GRAVY",
            "PARCEL EGG CHAPATHI",
            "CHANNA CHAPATHI & GRAVY",
            "PARCEL CHANNA CHAPATHI",
            "ADDITIONAL CHAPPATHI",
            "NONVEG GRAVY MT",
            "VEG GRAVY MT",
            "KARAPANIYARAM",
            "PAR PANIYARAM",
            "EXTRA PANIYARAM",
            "PAROTTA & VEG GREVY",
            "PAR PAROTTA & VEG GRAVY",
            "EXTRA PAROTTA",
            "CHAPPATHI VEG",
            "PARCEL VEG CHAPPATHI",
            "COCONUT BUN ROLL",
            "CHICKEN BIRIYANI WITH EGG",
            "PARCEL CHIC BIRIYANI WITH EGG",
            "VEG BRIYANI",
            "PARCEL VEG BRIYANI",
            "PARCEL EGG FRIED RICE",
            "EGG FRIED RICE",
            "PAR VEG FRIED RICE",
            "VEG FRIED RICE",
            "CHI FRIED RICE",
            "PAR CHI FRI RICE",
            "EGG NOODLES",
            "PARCEL EGG NOODLES",
            "VEG NOODLES",
            "PARCEL VEG NOODLES",
            "PAR KUSKA",
            "KUSKA",
            "PARCEL KUSHKA WITH EGG",
            "KUSKA WITH EGG"
        ]
    }
];

export const locationMapping = {
    'canteen 1': 'S Block',
    'four corner': 'Fourth Corner',
    'fourth corner': 'Fourth Corner',
    's-block': 'S Block',
    's black': 'S Block',
    'unit 3': 'Unit 3',
    'unit-3': 'Unit 3',
    'unit 3 fabeats': 'Unit 3 Fabeats',
    'unit-3 fabeats': 'Unit 3 Fabeats',
    'unit 1 yummy tummy': 'Unit-1 Yummy Tummy',
    'unit-1 yummy tummy': 'Unit-1 Yummy Tummy',
    'yummy tummy': 'Unit-1 Yummy Tummy',
    'central mess': 'Central Mess',
    'bakery': 'Bakery'
};
