export const CATEGORY_ITEMS = {
    "ICE CREAMS": [
        "KESAR PISTA - 50 ML - ICONE", "COTTON CANDY - 50ML ICONE", "CHOCOLATE - 50 ML ICONE", "VANNILA - CUP 60 ML SMALL",
        "VANNILA - 50 ML ICONE", "MANGO - 30ML ICONE", "TOFFEE - 30ML ICONE", "CHOCOLATE - CUP 85 ML",
        "RASPBERRY CHOCOLATE TRUFFLE", "VANNILA - CUP 85 ML", "CHOCOBAR 55 ML", "CHOCOBAR",
        "2-IN-1 STRAWBERRY&BLACK CURENT", "2-IN-1 MANGO & VANNILA", "SPIRAL MANGO & LITCHI",
        "SPIRAL WILBERRY,PINEAPPLE & VANNILA", "JOLLY TRAIN", "FUN WHEEL", "LILLTLE LOVE", "YUMY BEARS ROLL",
        "BERRY HEARTS", "MINI CHOCOBAR", "VANILLA BITES", "RED VELVET", "CHOCO TOFFEE", "COTTON CANDY",
        "WATERMELON STICK", "LYCHEE BITES", "RASBERRY BITES", "BAZOOKA(PINAPPLE&JAMUN BAR)",
        "TRIPLES(LEMON ORANGE&MINT)", "NEAPOLITAN(VANNILA STRAWBERRY)", "LIKSTICK ORANGE BAR 50ML",
        "LIKSTICK APPLE BAR 50ML", "LIKSTICK MANGO BAR 50ML", "LIKSTICK GRAPE BAR 50ML",
        "ARUN MALAI KULFI BAR 55ML", "STRAWBERRY CUP 60ML", "IC STRAWBERRY SHAKE 90ML",
        "IC COTTON CANDY SHAKE 90ML", "IC CHOCOLATE SHAKE 90ML", "IC MANGO SHAKE 90ML",
        "IC SW RECTANGLE 30ML", "IC SW COOKIE & CREAM 60ML", "COTTON CANDY WHALE BAR",
        "CHOCO BUTTERSCTOCH SMILY", "TRIO (RASP VANILLA MANGO) BAR", "Mango Delite",
        "STRAWBERRY CHEESE ICONE", "BLACK CURRANT ICONE 60ML", "BUTTERSCOTCH ICONE 100ML",
        "DOUBLE CHOCOLATE ICONE 100ML", "Belgium Chocolate", "RED VELVET ICONE 100ML",
        "VANILLA ICONE 100ML", "BUTTERSCOTCH CUP 125ML", "ITALIAN DELIGHT CUP 125ML",
        "VANILLA CUP 125ML", "MILK FANTACY CUP 40ML", "CASATA SLICE EXOTIC 120ML",
        "MANGO CUP 125ML", "POPITOS APPLE BAR 22ML", "KACCHA MANGO CUP 22ML",
        "MINI BALL CHOCOLATE", "MINI BALL VANNILA", "FRUIT CRÈME CUP", "RICH CHOC CUP 40ML",
        "COTTON CANDY PUSHUP", "BLACK CURRANT CUP 125 ML", "BELGIAN DONUT", "COTTON CANDY CONE",
        "IC SW CHOCO CAREMEL PENUT SAN", "IC SW REDVELVET SANDWICH 70ML", "MANGO BAR",
        "DONUT - COOKIE & CREAM 15 ML"
    ],
    "COOLDRINKS": [
        "MOUNTAIN DEW", "MIRINDA(Bottle)", "7UP", "PEPSI", "CHOCOLATE MILK SHAKE",
        "BELGIAN CHOCO MILKSHAKE", "VANNILA MILKSHAKE", "STRAWBERRY MILKSHAKE", "COLD COFFEE",
        "ROSE LASSY", "KESAR MILK", "BUTTER SCOTCH MILK SHAKE", "ORANGE CREAM SHAKE",
        "PREMIUM MALT", "ROSE MILK", "BADAM MILK", "1 RS CHOCOLATE", "1 RS ECLAIRS",
        "GALAXY CHOCOLATE", "20 RS CHOCOLATE (SNICKERS)", "35 RS CHOCOLATE (snickers)-brown",
        "DOUBLE MINT", "TROPICANA- APPLE TETRA", "TROPICANA- APPLE", "TETRA APPLE",
        "TETRA GUAVA", "TETRA LITCHI", "TETRA MANGO", "TETRA SLICE", "TETRA MIXED FRUIT",
        "SLICE(BOTTLE)", "NIMBOOZ TETRA", "7 UP (NIMBOOZ)", "TROPICANA - MIXED",
        "TROPICANA- GUAVA", "MAA APPLE", "MAA - MANGO", "TROPICANA - LITCHI",
        "TROPICANA - POMOGRANATE", "TROPICANA - ORANGE", "WATER BOTTLE", "MAAZA(BOTTLE)250ML",
        "TETRA-MAAZA", "THUMS UP (BOTTLE)250ML", "FANTA -BOTTLE 250ML", "FANTA - TIN 300ML",
        "COCA COLA -BOTTLE 250ML", "COCA COLA -TIN 300ML", "LIMCA - BOTTLE 250ML",
        "LIMCA - TIN 300ML", "SPRITE -BOTTLE 250ML", "SPRITE - TIN 300ML",
        "PULPY - ORANGE - BOTTLE", "KINLEY WATER BOTTLE - 500ML", "KINLEY WATER BOTTLE - 1LT",
        "MILK BADAM", "MILK ROSE", "MILK CHOCOLATE", "WATERMELON FRUIT"
    ],
    "SNACKS": [
        "SAMOSA", "EGG BONDA", "NORTH INDIAN SAMOSA", "CHILLIBAJJI", "BREAD BAJJI",
        "VAZHAKAI BAJJI", "ULUNTHU VADAI", "POTATO BONDA", "PARUPPU VADAI", "NORMAL OMLETE",
        "Black sundal", "ONION BONDA", "BREAD OMLET", "PLAIN OMLETE"
    ],
    "BAKERY ITEMS": [
        "EGG PUFFS", "VEG. PUFFS", "PANNEER PUFFS", "CHICKEN PUFFS", "CHICKEN SANDWICH",
        "PUTTING CAKE", "TEA CAKE", "COCANUT BUN", "COCONUT BUN ROLL", "BREAD", "WHEAT BREAD"
    ],
    "OTHERS": ["TEA", "TEA (Excess)", "COFFEE"],
    "COMBO PACK SALES": [
        "TEA WITH EGG PUFFS", "TEA WITH PUDDING CAKE", "TEA WITH SAMOSA 2 NOS",
        "CHICKEN ROLL WITH PEPSI", "CHICKEN ROLL WITH 7 UP", "CHICKEN ROLL WITH MIRANDA",
        "CHICKEN ROLL WITH MOUNTAINDEW"
    ],
    "BREAKFAST": [
        "RAVA KITCHADI", "RAVA KITCHADI (Parcel)", "ROAST", "EXTRA DOSA", "PARCEL DOSA",
        "IDIYAPPAM", "PARCEL IDIYAPPAM", "EXTRA IDIYAPPAM", "POORI MASAL", "EXTRA POORI", "PARCEL POORI"
    ],
    "LUNCH": [
        "CURD RICE", "TOMOTA RICE", "PAR CURD RICE", "PAR TOMOTA RICE", "CHICKEN CHAPPATHY & GRAVY",
        "PARCEL CHICKEN CHAPPATHI", "PANNEER CHAPPATHI & GRAVY", "PARCEL PANNEER CHAPPATHI",
        "EGG CHAPATHI & GRAVY", "PARCEL EGG CHAPATHI", "CHANNA CHAPATHI & GRAVY",
        "PARCEL CHANNA CHAPATHI", "ADDITIONAL CHAPPATHI", "NONVEG GRAVY MT", "VEG GRAVY MT",
        "KARAPANIYARAM", "PAR PANIYARAM", "EXTRA PANIYARAM", "PAROTTA & VEG GREVY",
        "PAR PAROTTA & VEG GRAVY", "EXTRA PAROTTA", "CHAPPATHI VEG", "PARCEL VEG CHAPPATHI",
        "CHICKEN BIRIYANI WITH EGG", "PARCEL CHIC BRIYANI WITH EGG", "VEG BRIYANI",
        "PARCEL VEG BRIYANI", "EGG FRIED RICE", "PARCEL EGG FRIED RICE", "VEG FRIED RICE",
        "PAR VEG FRIED RICE", "CHI FRIED RICE", "PAR CHI FRI RICE", "EGG NOODLES",
        "PARCEL EGG NOODLES", "VEG NODDLES", "PARCEL VEG NODDLES", "KUSKA", "PAR KUSKA",
        "KUSKA WITH EGG", "PARCEL KUSHKA WITH EGG"
    ]
};
